{% set name = "django-tree-queries" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_tree_queries-{{ version }}.tar.gz
  sha256: d1325e75f96e90b86c4316a3d63498101ec05703f4e629786b561e8aaab0e4a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install ./py/h2o_wave -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - tree_queries
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Tree queries with explicit opt-in, without configurability
  home: https://github.com/feincms/django-tree-queries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
