{% set name = "django-tree-queries" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_tree_queries-{{ version }}.tar.gz
  sha256: db2d97728354fca0a40b5e9118c2ff9ab5187abfc9fc54680af89d911b0ec1da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - django-js-asset
    - django
    - python >={{ python_min }}

test:
  imports:
    - tree_queries
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Tree queries with explicit opt-in, without configurability
  home: https://github.com/feincms/django-tree-queries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
