{% set name = "django-tree-queries" %}
{% set version = "0.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_tree_queries-{{ version }}.tar.gz
  sha256: 3ede5a594cb439a99a90ae12b6a40e609e4e4e87a6bf9b7681204ccb5884415a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - django-js-asset
    - django
    - python >={{ python_min }}

test:
  imports:
    - tree_queries
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Tree queries with explicit opt-in, without configurability
  home: https://github.com/feincms/django-tree-queries
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
